default_language_version:
  python: python3.8

repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: '84c95766e679710d9a0fa910a1cd276c87be42c5'
    hooks:
      - id: flake8

  - repo: https://github.com/ambv/black
    rev: 21.5b0
    hooks:
      - id: black
        args: [-tpy38, -q, -l79, --check]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        types: [python]
        args: [-l79, -m3, --trailing-comma, --ignore-whitespace]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: ^test/
        args: [--disallow-untyped-defs, --disallow-untyped-calls, --disallow-incomplete-defs]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D200,D202,D205,D212,D213,D400,D401,D415
          - --match-dir="[^(\.|migrations)].*"
