openapi: '3.0.3'
info:
  title: Tesselo Giges integrations API
  description: 'One giant with 50 heads and 100 arms'
  version: 0.0.1
  contact:
    name: Tesselo integrations
    x-slack: '#tech-team'

servers:
  - url: /
    description: Giges API

security: []

components:
  schemas:
    AsanaEventWebhookBody:
      title: Asana Event Webhook Body
      type: object
      required:
        - events
      properties:
        events:
          type: array
          items:
            description: Asana Event
            type: object

    AsanaEventWebhookEmptyBody:
      title: Asana Event Webhook Empty Body
      type: object


  parameters:
    HookSecretHeader:
      name: x-hook-secret
      description: Provided secret to stablish a webhook
      in: header
      schema:
        type: string

    HookSignatureHeader:
      name: x-hook-signature
      description: Computed signature for a webhook event
      in: header
      schema:
        type: string

paths:
  /ping:
    get:
      tags: [Health]
      operationId: giges.handlers.health.ping
      summary: Pong that ping
      responses:
        200:
          description: 'Health check result'
          content:
            application/json:
              schema:
                type: object
                properties:
                  pong:
                    type: boolean
  /asana/projects/{project_id}:
    post:
      tags: [Asana]
      operationId: giges.handlers.asana.task_webhook
      summary: Asana Project webhook
      parameters:
        - $ref: '#/components/parameters/HookSecretHeader'
        - $ref: '#/components/parameters/HookSignatureHeader'
        - in: path
          name: project_id
          description: Asana Project ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/AsanaEventWebhookBody'
                - $ref: '#/components/schemas/AsanaEventWebhookEmptyBody'
      responses:
        204:
          description: 'Webhook handled correctly'
        400:
          description: 'Webhook handling format error'
        404:
          description: 'Webhook or Project not configured'
  /asana/workflows/{project_id}:
    post:
      tags: [Asana]
      operationId: giges.handlers.asana.customer_webhook
      summary: Asana Workflow webhook
      parameters:
        - $ref: '#/components/parameters/HookSecretHeader'
        - $ref: '#/components/parameters/HookSignatureHeader'
        - in: path
          name: project_id
          description: Asana Project ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/AsanaEventWebhookBody'
                - $ref: '#/components/schemas/AsanaEventWebhookEmptyBody'
      responses:
        204:
          description: 'Webhook handled correctly'
        400:
          description: 'Webhook handling format error'
        404:
          description: 'Webhook or Project not configured'

  /slack/commands/ritual:
    post:
      tags: [Slack, Tesserito]
      operationId: giges.handlers.slack.start_ritual
      summary: Start the conversation and log for a ritual
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              additionalProperties: true
              properties:
                channel_id:
                  description: The Slack channel ID yes
                token:
                  description: Some token I still do not know how to use
                channel_name:
                  description: The human Slack channel name
                user_id:
                  description: The slack ID for the user
                command:
                  description: The unused slack component with the command
                text:
                  description: Everything after the command that the user entered
                response_url:
                  description: An ephemeral URL where we can send slow responses
                api_app_id:
                  description: Something that will most likely be needed later
                team_id:
                  description: The slack team ID
                team_domain:
                  description: The slack team domain
                enterprise_id:
                  description: The slack enterprise ID
                enterprise_name:
                  description: The slack enterprise name
                user_name:
                  description: The slack user name
                trigger_id:
                  description: The slack trigger ID

      responses:
        200:
          description: 'Command received, slack'
          content:
            application/json:
              schema:
                type: object
        400:
          description: 'Command bad formatted'
        404:
          description: 'That ritual does not exist'
