"""Initial models

Revision ID: a6a81fe8dbf0
Revises:
Create Date: 2021-08-12 19:50:16.079002

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a6a81fe8dbf0"
down_revision = None
branch_labels = None
depends_on = None

resource_type_enum = postgresql.ENUM(
    "custom_field",
    "enum_option",
    "project",
    "task",
    "webhook",
    "workspace",
    name="resource_type_enum",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asana_project",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asana_project_external_id"),
        "asana_project",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asana_project_name"), "asana_project", ["name"], unique=False
    )
    op.create_table(
        "asana_webhook",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column(
            "resource_type",
            resource_type_enum,
            nullable=True,
        ),
        sa.Column("secret", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asana_webhook_external_id"),
        "asana_webhook",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asana_webhook_path"), "asana_webhook", ["path"], unique=False
    )
    op.create_table(
        "asana_event",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("webhook_id", sa.CHAR(length=36), nullable=True),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["asana_webhook.id"],
            name="asana_event_webhook_fk",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asana_event")
    op.drop_index(op.f("ix_asana_webhook_path"), table_name="asana_webhook")
    op.drop_index(
        op.f("ix_asana_webhook_external_id"), table_name="asana_webhook"
    )
    op.drop_table("asana_webhook")
    op.drop_index(op.f("ix_asana_project_name"), table_name="asana_project")
    op.drop_index(
        op.f("ix_asana_project_external_id"), table_name="asana_project"
    )
    op.drop_table("asana_project")
    resource_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
