"""Ritual model

Revision ID: be1d877dee9b
Revises: 98abb3966af0
Create Date: 2022-04-29 11:40:49.096482

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be1d877dee9b"
down_revision = "98abb3966af0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ritual",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("team_id", sa.CHAR(length=36), nullable=True),
        sa.Column("logs_url", sa.String(), nullable=True),
        sa.Column("meeting_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
            name="ritual_team_fk",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ritual_logs_url"), "ritual", ["logs_url"], unique=False
    )
    op.create_index(op.f("ix_ritual_name"), "ritual", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ritual_name"), table_name="ritual")
    op.drop_index(op.f("ix_ritual_logs_url"), table_name="ritual")
    op.drop_table("ritual")
    # ### end Alembic commands ###
